events {
    worker_connections 1024;
}

http {
    upstream backend_node {
        server backend-node:5001;
    }

    upstream assistant_chatbot {
        server assistant-chatbot:8080;
    }

    upstream realtime_voice {
        server realtime-voice:5000;
    }

    server {
        listen 80;

        location /api/query {
            proxy_pass http://assistant_chatbot;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /process_conversation {
            proxy_pass http://realtime_voice;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /socket.io/ {
            proxy_pass http://realtime_voice;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }

        location / {
            proxy_pass http://backend_node;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
